// =============================================================================
// IAMS — shared/services/letters.js
// =============================================================================
// "insert letter metadata, count query" — per Section 10's one-line summary.
// Letters are never updated or deleted in Phase 1 (the audit log is
// immutable — rls-policies.sql has no UPDATE/DELETE policy on this table,
// and a regenerated letter is a brand new row with a new verification_code,
// per FR2: "If a student loses the downloaded file, they may regenerate the
// letter — this will increment their letter count.").
//
// The actual PDF assembly (jsPDF + signed-URL asset fetch) lives in
// shared/pdf/generate-letter.js, not here — this file only ever talks to
// the `letters` table and the verify_letter RPC.
// =============================================================================

import { supabase } from '../supabase-client.js';
import { generateUuid, generateVerificationCode, isValidVerificationCode, validateAddressFields } from '../utils.js';

/** Returns every letter for the signed-in student, most recent first. Admin sees all (audit — FR7). */
export async function listLetters() {
  const { data, error } = await supabase.from('letters').select('*').order('generated_at', { ascending: false });
  return { data, error };
}

/** Returns letters for a specific student — used by the admin's letters-audit screen (FR7: "audit all letters generated by any student at any time"). */
export async function listLettersForStudent(studentId) {
  const { data, error } = await supabase
    .from('letters')
    .select('*')
    .eq('student_id', studentId)
    .order('generated_at', { ascending: false });
  return { data, error };
}

/** Returns letters for a specific season — for the per-season audit total in FR7. */
export async function listLettersForSeason(seasonId) {
  const { data, error } = await supabase
    .from('letters')
    .select('*')
    .eq('season_id', seasonId)
    .order('generated_at', { ascending: false });
  return { data, error };
}

/**
 * Returns the signed-in student's live letter count, scoped to one season
 * — exactly the number FR2 says drives the escalating visual styling
 * (neutral -> amber -> red, see utils.letterCountTier). "Computed live
 * (COUNT(*) scoped to the active season), not persisted or enforced"
 * (Section 9.7) — this fetches the full row set and counts client-side
 * rather than relying on a server-side count aggregate, since the mock
 * client's documented query surface (mock-client.js) doesn't expose one;
 * a real Supabase deployment could swap this for `.select('*', { count:
 * 'exact', head: true })` without changing the function's contract.
 */
export async function getLetterCountForSeason(studentId, seasonId) {
  const { data, error } = await supabase.from('letters').select('id').eq('student_id', studentId).eq('season_id', seasonId);
  if (error) return { count: null, error };
  return { count: data.length, error: null };
}

/**
 * Generates a fresh, format-valid verification code. Collision against an
 * existing code is vanishingly unlikely (8 chars, 36^8 space) but not
 * impossible — generateLetter() below still surfaces a server-side
 * uniqueness error if one ever occurs, rather than this function silently
 * retrying and masking a real problem.
 */
function newVerificationCode() {
  const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
  let code = '';
  for (let i = 0; i < 8; i++) code += chars[Math.floor(Math.random() * chars.length)];
  return code;
}

/**
 * Records a new letter (insert only — the PDF itself is generated and
 * downloaded client-side by shared/pdf/generate-letter.js, never uploaded
 * here). `row` needs student_id, season_id, company_name, region,
 * city_town, street_landmark, contact_person, company_contact_phone.
 *
 * RLS only permits this while the given season is 'open' ("letters:
 * student inserts own") — a closed/archived season will be rejected
 * server-side. Generates and validates its own verification_code so
 * callers don't have to import the format separately from
 * isValidVerificationCode.
 */
export async function generateLetter(row) {
  const addressProblems = validateAddressFields(row);
  if (addressProblems.length > 0) {
    return { data: null, error: { message: `Missing required address field(s): ${addressProblems.join(', ')}` } };
  }
  if (!row.company_name?.trim()) {
    return { data: null, error: { message: 'Company name is required.' } };
  }

  const verification_code = newVerificationCode();
  if (!isValidVerificationCode(verification_code)) {
    // Should be unreachable given newVerificationCode()'s alphabet, but
    // checked explicitly so a future change to that function can't
    // silently produce codes the DB constraint would reject.
    return { data: null, error: { message: 'Generated verification code failed format validation — this is a bug.' } };
  }

  const payload = { id: generateUuid(), ...row, verification_code };
  const { data, error } = await supabase.from('letters').insert(payload).select().single();
  return { data, error };
}

/**
 * Public alias used by the updated student letters flow:
 *   1. Generates verification_code client-side.
 *   2. Inserts into `letters` table.
 *   3. Returns { data: insertedRow, error }.
 *
 * The caller (student/letters.js) passes the returned row's
 * verification_code and generated_at into generateAndDownloadLetter().
 */
export async function createLetter(formData) {
  return generateLetter(formData);
}

/**
 * Public letter verification lookup (FR2: "a short verification code...
 * linking to a public lookup page"). Calls the verify_letter RPC rather
 * than querying the letters table directly, since this is meant to be
 * reachable from an unauthenticated /verify/{code} page — the RPC is the
 * one piece of this domain that doesn't go through RLS-scoped table
 * access. Returns null if the code doesn't match any letter (mirrors the
 * RPC's documented behavior: "zero rows, not an error, for an unknown
 * code").
 */
export async function verifyLetterCode(code) {
  const { data, error } = await supabase.rpc('verify_letter', { p_code: code });
  if (error) return { data: null, error };
  return { data: data?.[0] ?? null, error: null };
}
